"""Update enrollments schema

Revision ID: b8bc18023922
Revises: 
Create Date: 2025-03-31 14:14:15.456114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bc18023922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollments', 'Enrollment_id',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_index('ix_enrollments_student_id', table_name='enrollments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enrollments_student_id', 'enrollments', ['student_id'], unique=False)
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.alter_column('enrollments', 'Enrollment_id',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
